services:
  - type: web
    name: pg-stay-backend
    runtime: node
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: USE_SINGLE_DB
        value: "true"
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        value: postgresql://pgstay_user:GeciW9JMFkveJIGIGFQk9co0vVOeXwXx@dpg-d79uc295pdvs73bpn5t0-a/pgstay_prod_7iuu
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: SUPER_ADMIN_EMAIL
        value: superadmin@pgstay.com
      - key: SUPER_ADMIN_PASSWORD
        value: superadmin123

databases:
  - name: pg-stay-db
    databaseName: pgstay_prod
    user: pgstay_user
    region: oregon
    plan: free
